-- 6 sports
INSERT INTO sports (sportName, sportDesc) VALUES ('Basketball','Players attempt to shoot the ball through the hoop on the opponent''s court, moving the ball by throwing and dribbling.');
INSERT INTO sports (sportName, sportDesc) VALUES ('Volleyball','A game for two teams of six players, in which a large ball is hit by hand over a high net, the aim being to score points by making the ball reach the ground on the opponent''s side of the court.');
INSERT INTO sports (sportName, sportDesc) VALUES ('Baseball','A bat and ball game in which the aim is to hit the ball and score runs by running around four bases.');
INSERT INTO sports (sportName, sportDesc) VALUES ('Soccer','Played between two teams of eleven players with a spherical ball. The game is played on a rectangular field with a goal at each end. The object is to score by using any part of the body except the arms and hands to get the ball into the opposing goal.');
INSERT INTO sports (sportName, sportDesc) VALUES ('Football','A team sport played on a rectangular field with goalposts at each end. Each team attempts to advance an oval ball down the field into the end zone by running or passing it.');
INSERT INTO sports (sportName, sportDesc) VALUES ('3x3 Basketball', 'A variation of basketball played on a half-court with just three players on each team.');

-- All passwords are asdf. 40 users
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('leka5026', 'leo', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, email, phone, gender) VALUES ('thbr4871', 'theo', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11', 'thbr4871@colorado.edu', '7202994398', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('zach2898', 'zach', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('jafr7644', 'jacob', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('japa2103', 'jaxon', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('brsa1000', 'brendan', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender, phone) VALUES ('nimo1000', 'nick', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11', 'Male', '1234567890');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender, phone) VALUES ('dede1000', 'destry', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11', 'Male', '0987654321');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender, phone) VALUES ('mimc1000', 'michael', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11', 'Male', '6548760981');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('cabi1000', 'carson', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2026, 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Cristiano_Ronaldo_2018.jpg', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('aufu1000', 'audrey', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2026, '', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('jacl1000', 'jackie', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/xpcd6auodk3w0vda6jal', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('keol1000', 'kendall', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('frla1000', 'francesca', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender, phone) VALUES ('juda1000', 'julia', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11', 'Female', '3334445555');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('brvi1000', 'bryce', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSheZXnf27LhoKkcVFu_IbieY6fXIRG4U1Dvj8EMoH_qyWZyHtv', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('olda1000', 'olivia', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2026, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQdMDiqObzp_5v0L6Y6qkBtnAr9hGpEYsGqPXwcmCQuw0AG3ydlYIuO1jRaI7eo_2KFic&usqp=CAU', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('jebu1000', 'jessie', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11', 'Other/Prefer not to say');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('pewo1000', 'peter', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, 'https://www.atptour.com/-/media/tennis/players/gladiator/2020/03/23/10/19/federer_full_ao20.png', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('empu1000', 'emma', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('iztu1000', 'izzy', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('coru1000', 'cole', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, 'http://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQTBIkxproxJHBsj2ZOkeFr3CYyVJjrfW8qcovw9whTrkRjsqYnBRlprpmyAknfOsug43oiT9iqS9cJe6s', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender, phone) VALUES ('cosm1000', 'cole', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11', 'Male', '00011122222');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('keri1000', 'kenton', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, 'https://imageio.forbes.com/specials-images/imageserve/627bd323672c41ea74c88a13/0x0.jpg?format=jpg&crop=1834,1833,x583,y167,safe&height=416&width=416&fit=bounds', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender, phone) VALUES ('olsh1000', 'oliver', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, 'https://pga-tour-res.cloudinary.com/image/upload/c_fill,d_headshots_default.png,dpr_3.0,f_auto,g_face:center,h_350,q_auto,w_280/headshots_08793.png', '2022-11-11', 'Male', '8713326721');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender, phone) VALUES ('chpe1000', 'chas', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11', 'Male', '0973421289');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('koba1000', 'kole', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCuJs_eD_YYejFPtXMkp_WhRW41Xz0DSlxtmImgsOq5hUMjDJ1', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender, phone) VALUES ('alse1000', 'alex', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11', 'Other/Prefer not to say', '2680402880');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('alka1000', 'alex', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Rafael_Nadal_10%2C_Aegon_Championships%2C_London%2C_UK_-_Diliff_%28cropped%29.jpg', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('iska1000', 'isaac', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2026, 'https://cdn.nba.com/headshots/nba/latest/1040x760/201142.png', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('luka1000', 'lucy', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2026, '', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('frka1000', 'fred', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender, phone) VALUES ('tsch1000', 'tsion', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11', 'Male', '6902216774');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('moka1000', 'moira', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('deos1000', 'devyn', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('kixx1000', 'ki', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, 'https://b.fssta.com/uploads/application/soccer/headshots/713.png', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('tixx1000', 'ti', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2026, '', '2022-11-11', 'Male');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('chtr1000', 'chloe', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('maka1000', 'marine', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11', 'Female');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate, gender) VALUES ('camo1000', 'carolina', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11', 'Female');

-- 20 teams
INSERT INTO teams (teamName) VALUES ('Alpha Sonics');
INSERT INTO teams (teamName) VALUES ('Venomous Busters');
INSERT INTO teams (teamName) VALUES ('Ghost Piledrivers');
INSERT INTO teams (teamName) VALUES ('Carnivore Xpress');
INSERT INTO teams (teamName) VALUES ('Silent Bombers');
INSERT INTO teams (teamName) VALUES ('Aero Planets');
INSERT INTO teams (teamName) VALUES ('Fire United');
INSERT INTO teams (teamName) VALUES ('Quicksilver Bullets');
INSERT INTO teams (teamName) VALUES ('Skull Buccaneers');
INSERT INTO teams (teamName) VALUES ('Blue Dreamers');
INSERT INTO teams (teamName) VALUES ('Reptile Assassins');
INSERT INTO teams (teamName) VALUES ('Zulu Bulls');
INSERT INTO teams (teamName) VALUES ('Samurai Spiders');
INSERT INTO teams (teamName) VALUES ('Aero Predators');
INSERT INTO teams (teamName) VALUES ('Knockout Bullets');
INSERT INTO teams (teamName) VALUES ('Dolphin Secret Agents');
INSERT INTO teams (teamName) VALUES ('Crimson Commando Squad');
INSERT INTO teams (teamName) VALUES ('Spinning Rebels');
INSERT INTO teams (teamName) VALUES ('Shaolin Sharpshooters');
INSERT INTO teams (teamName) VALUES ('Kamikaze Chuckers');

-- 100 games
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-20', '12:00', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-21', '12:05', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-22', '12:10', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-23', '12:15', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-24', '12:30', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-25', '12:45', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-26', '13:00', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-27', '13:05', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-28', '13:10', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-29', '13:15', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-30', '12:00', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-01', '12:05', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-02', '12:10', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-03', '12:15', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-04', '12:00', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-05', '12:30', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-06', '12:45', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-07', '13:00', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-08', '13:05', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-09', '13:15', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-10', '12:00', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-11', '12:05', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-12', '12:10', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-13', '12:15', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-14', '12:00', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-15', '12:30', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-16', '12:45', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-17', '13:00', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-18', '13:05', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-19', '13:15', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-20', '12:00', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-21', '12:05', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-22', '12:10', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-23', '12:15', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-24', '12:00', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-25', '12:30', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-26', '12:45', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-27', '13:00', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-28', '13:05', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-29', '13:15', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-30', '12:00', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-01', '12:05', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-02', '12:10', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-03', '12:15', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-04', '12:00', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-05', '12:30', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-06', '12:45', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-07', '13:00', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-08', '13:05', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-09', '13:15', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-10', '12:00', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-11', '12:05', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-12', '12:10', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-13', '12:15', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-14', '12:00', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-15', '12:30', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-16', '12:45', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-17', '13:00', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-18', '13:05', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-19', '13:15', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-20', '12:00', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-21', '12:05', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-22', '12:10', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-23', '12:15', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-24', '12:00', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-25', '12:30', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-26', '12:45', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-27', '13:00', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-28', '13:05', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-29', '13:15', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-30', '12:00', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-01', '12:05', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-02', '12:10', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-03', '12:15', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-04', '12:00', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-05', '12:30', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-06', '12:45', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-07', '13:00', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-08', '13:05', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-09', '13:15', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-10', '12:00', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-11', '12:05', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-12', '12:10', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-13', '12:15', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-14', '12:00', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-15', '12:30', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-16', '12:45', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-17', '13:00', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-18', '13:05', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-19', '13:15', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-20', '12:00', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-21', '12:05', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-22', '12:10', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-23', '12:15', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-24', '12:00', 'Franklin Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-25', '12:30', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-26', '12:45', 'Main Rec');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-27', '13:00', 'Scott Carpenter Park');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-28', '13:05', 'Kittredge Field');
INSERT INTO games (gameDate, time, location) VALUES ('2023-03-01', '13:15', 'Franklin Field');

-- 20 Teams so 40 relations
INSERT INTO teamsToSports (teamID, sportID) VALUES (1, 1);
INSERT INTO teamsToSports (teamID, sportID) VALUES (2, 1);
INSERT INTO teamsToSports (teamID, sportID) VALUES (3, 1);
INSERT INTO teamsToSports (teamID, sportID) VALUES (4, 1);
INSERT INTO teamsToSports (teamID, sportID) VALUES (5, 2);
INSERT INTO teamsToSports (teamID, sportID) VALUES (6, 2);
INSERT INTO teamsToSports (teamID, sportID) VALUES (7, 2);
INSERT INTO teamsToSports (teamID, sportID) VALUES (8, 2);
INSERT INTO teamsToSports (teamID, sportID) VALUES (9, 3);
INSERT INTO teamsToSports (teamID, sportID) VALUES (10, 3);
INSERT INTO teamsToSports (teamID, sportID) VALUES (11, 3);
INSERT INTO teamsToSports (teamID, sportID) VALUES (12, 3);
INSERT INTO teamsToSports (teamID, sportID) VALUES (13, 4);
INSERT INTO teamsToSports (teamID, sportID) VALUES (14, 4);
INSERT INTO teamsToSports (teamID, sportID) VALUES (15, 4);
INSERT INTO teamsToSports (teamID, sportID) VALUES (16, 4);
INSERT INTO teamsToSports (teamID, sportID) VALUES (17, 5);
INSERT INTO teamsToSports (teamID, sportID) VALUES (18, 5);
INSERT INTO teamsToSports (teamID, sportID) VALUES (19, 5);
INSERT INTO teamsToSports (teamID, sportID) VALUES (20, 5);

-- 100 Games, 2 teams per game, so 200 Relations
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 1); 
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 1); 
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 6);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 6);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 11);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 11);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 16);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 16);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 21);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 21);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 26);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 26);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 31);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 31);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 36);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 36);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 41);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 41);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 46);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 46);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 51);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 51);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 56);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 56);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 61);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 61);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 66);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 66);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 71);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 71);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 76);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 76);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 81);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 81);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 86);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 86);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 91);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 91);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 96);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 96);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 2);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 2);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 7);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 7);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 12);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 12);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 17);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 17);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 22);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 22);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 27);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 27);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 32);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 32);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 37);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 37);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 42);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 42);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 47);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 47);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 52);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 52);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 57);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 57);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 62);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 62);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 67);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 67);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 72);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 72);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 77);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 77);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 82);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 82);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 87);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 87);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 92);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 92);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 97);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 97);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 3);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 3);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 8);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 8);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 13);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 13);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 18);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 18);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 23);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 23);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 28);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 28);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 33);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 33);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 38);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 38);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 43);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 43);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 48);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 48);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 53);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 53);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 58);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 58);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 63);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 63);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 68);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 68);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 73);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 73);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 78);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 78);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 83);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 83);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 88);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 88);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 93);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 93);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 98);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 98);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 4);
INSERT INTO teamsToGames (teamID, gameID) VALUES (16, 4);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 9);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 9);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 14);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 14);
INSERT INTO teamsToGames (teamID, gameID) VALUES (16, 19);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 19);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 24);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 24);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 29);
INSERT INTO teamsToGames (teamID, gameID) VALUES (16, 29);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 34);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 34);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 39);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 39);
INSERT INTO teamsToGames (teamID, gameID) VALUES (16, 44);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 44);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 49);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 49);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 54);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 54);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 59);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 59);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 64);
INSERT INTO teamsToGames (teamID, gameID) VALUES (16, 64);
INSERT INTO teamsToGames (teamID, gameID) VALUES (16, 69);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 69);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 74);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 74);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 79);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 79);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 84);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 84);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 89);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 89);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 94);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 94);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 99);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 99);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 5);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 5);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 10);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 10);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 15);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 15);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 20);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 20);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 25);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 25);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 30);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 30);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 35);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 35);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 40);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 40);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 45);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 45);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 50);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 50);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 55);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 55);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 60);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 60);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 65);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 65);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 70);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 70);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 75);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 75);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 80);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 80);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 85);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 85);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 90);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 90);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 95);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 95);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 100);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 100);

-- teams to players. 40 players 20 teams. have 5 people on each teach, so 100 relations
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (11, 1);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (25, 1);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (26, 1);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (4, 1);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (1, 1);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (19, 2);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (4, 2);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (9, 2);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (35, 2);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (36, 2);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (25, 3);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (24, 3);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (16, 3);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (7, 3);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (22, 3);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (37, 4);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (9, 4);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (7, 4);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (28, 4);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (1, 4);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (23, 5);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (18, 5);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (29, 5);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (33, 5);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (20, 5);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (3, 6);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (27, 6);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (38, 6);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (29, 6);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (11, 6);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (36, 7);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (16, 7);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (3, 7);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (34, 7);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (7, 7);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (24, 8);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (15, 8);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (40, 8);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (21, 8);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (18, 8);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (7, 9);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (38, 9);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (15, 9);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (4, 9);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (10, 9);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (8, 10);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (38, 10);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (12, 10);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (22, 10);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (21, 10);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (1, 11);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (27, 11);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (37, 11);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (17, 11);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (21, 11);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (29, 12);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (9, 12);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (15, 12);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (11, 12);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (33, 12);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (12, 13);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (18, 13);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (39, 13);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (27, 13);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (8, 13);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (28, 14);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (38, 14);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (23, 14);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (40, 14);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (17, 14);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (8, 15);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (14, 15);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (13, 15);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (35, 15);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (39, 15);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (23, 16);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (26, 16);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (7, 16);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (14, 16);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (8, 16);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (21, 17);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (13, 17);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (27, 17);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (24, 17);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (12, 17);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (27, 18);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (17, 18);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (28, 18);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (20, 18);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (15, 18);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (38, 19);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (18, 19);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (22, 19);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (5, 19);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (40, 19);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (2, 20);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (4, 20);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (10, 20);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (5, 20);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (15, 20);

-- Teams to Captains. 20 teams, each with 1 captain. 20 relatins
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (11, 1);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (19, 2);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (25, 3);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (37, 4);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (23, 5);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (3, 6);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (36, 7);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (24, 8);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (7, 9);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (8, 10);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (1, 11);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (29, 12);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (12, 13);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (28, 14);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (8, 15);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (23, 16);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (21, 17);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (27, 18);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (38, 19);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (2, 20);

INSERT INTO gamesToWinners (gameID, teamID) VALUES (1, 3); -- Players are: Team IDs [1,3] Team Names: [Alpha Sonics, Ghost Piledrivers]
INSERT INTO gamesToWinners (gameID, teamID) VALUES (2, 6); -- Players are: Team IDs [6,7] Team Names: [Aero Planets, Fire United]
INSERT INTO gamesToWinners (gameID, teamID) VALUES (3, 12); -- Players are: Team IDs [11,12] Team Names: [Reptile Assassins, Zulu Bulls]
INSERT INTO gamesToWinners (gameID, teamID) VALUES (4, 14); -- Players are: Team IDs [14,16] Team Names: [Aero Predators, Dolphin Secret Agents]
INSERT INTO gamesToWinners (gameID, teamID) VALUES (5, 20); -- Players are: Team IDs [19,20] Team Names: [Shaolin Sharpshooters, Kamikaze Chuckers]
INSERT INTO gamesToWinners (gameID, teamID) VALUES (6, 2); -- Players are: Team IDs [2,4] Team Names: [Venomous Busters, Carnivore Xpress]
INSERT INTO gamesToWinners (gameID, teamID) VALUES (7, 7); -- Players are: Team IDs [7,8] Team Names: [Fire United, Quicksilver Bullets]
